// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title KiyotakiWright — the emergence of money (search-theoretic abiogenesis)
 *
 * Executes: Kiyotaki & Wright, "On Money as a Medium of Exchange" (JPE 1989) —
 * money EMERGES as the good agents accept not to consume but to RE-TRADE, via a
 * self-fulfilling acceptance equilibrium. This is the rigorous form of
 * `docs/MONEY-ABIOGENESIS.md`: instead of *assuming* a tradeability τ (which KW
 * rightly criticised), acceptance is DERIVED from a value comparison plus a
 * feedback.
 *
 * Setup (the canonical minimal KW): 3 goods, 3 types. Type i produces good i and
 * consumes good (i+1) mod 3 — a want-cycle, so direct barter has no double
 * coincidence and an intermediary (money) must emerge.
 *
 * The decision (strategic, not assumed): accept a non-consumption good g
 * speculatively iff its MARKETABILITY (chance of re-trading it) exceeds its
 * HOLDING COST. The self-fulfilling feedback: more acceptors → higher
 * marketability → more acceptors. Money = the good that becomes universally
 * accepted.
 *
 * The framework's twist (the thing to SHOW): holding cost is driven by
 * LEDGER-likeness — a more divisible, more known-supply good is cheaper to hold
 * and re-trade. So the equilibrium SELECTS the most ledger-like good. The
 * abiogenesis claim, derived rather than decreed: *the most marketable good is
 * the most ledger-like.*
 *
 * Multiple equilibria (KW's hallmark): seed expectations high enough on a costly
 * good and you can sustain it as money anyway (a speculative equilibrium). The
 * ledger-like good is the *fundamental* outcome; expectations can override it.
 *
 * Honest scope: this is a MEAN-FIELD KW — it tracks each good's marketability and
 * updates by best-response + feedback, not agent-by-agent matching. Faithful in
 * mechanism (strategic speculative acceptance + self-fulfilling feedback +
 * ledger-driven cost); simplified in implementation. A deterministic, steppable
 * educational demonstrator — watch money precipitate.
 *
 *  NO FLOOR (canon guard): `ledger[g]` is a TRANSACTION-COST driver (resolution +
 *  integrity — which good is cheap to re-trade), NOT a value or a backing. What
 *  self-fulfilling acceptance drives here is SELECTION — *which* good becomes money —
 *  not money's *worth*: the worth is floorless-but-fruitful (the trades it unlocks,
 *  Stone 3 — generated by acceptance, not identical to it). Proof there is no floor:
 *  seed a costly, low-ledger good's expectations high enough and it becomes money
 *  anyway (the speculative equilibrium) — *selection* is acceptance-driven, and the
 *  ledger score only tilts the *fundamental* outcome, never grounds it. And there is
 *  NO consumption/use-value good here — KW's would-be commodity seed is stripped;
 *  emergence runs on ledger-cost + acceptance alone.
 */
contract KiyotakiWright {
    uint256 public constant SCALE = 10_000;   // basis points
    uint8   public constant G = 3;

    uint256[3] public ledger;          // ledger-likeness per good (divisibility + known supply); higher ⇒ lower cost
    uint256[3] public marketability;   // current acceptance probability per good (0..SCALE)
    bool[3]    public isMoney;          // has good g become universally accepted?
    uint256    public round;

    uint256 public adopt;              // how fast acceptance climbs when speculatively held
    uint256 public decay;              // how fast it falls back when not

    event Step(uint256 indexed round, uint256 m0, uint256 m1, uint256 m2);
    event MoneyEmerged(uint8 indexed good, uint256 round);

    // ledger0..2 = ledger-likeness of each good; seed0..2 = initial marketability (expectations)
    constructor(
        uint256 ledger0, uint256 ledger1, uint256 ledger2,
        uint256 seed0,   uint256 seed1,   uint256 seed2,
        uint256 _adopt,  uint256 _decay
    ) {
        ledger = [ledger0, ledger1, ledger2];
        marketability = [seed0, seed1, seed2];
        adopt = _adopt; decay = _decay;
    }

    function holdingCost(uint8 g) public view returns (uint256) {
        return SCALE - ledger[g];        // less ledger-like ⇒ costlier to hold/re-trade
    }

    function step() external { _step(); }
    function run(uint256 rounds) external { for (uint256 i = 0; i < rounds; i++) _step(); }

    // one round of best-response + self-fulfilling feedback
    function _step() internal {
        round++;
        for (uint8 g = 0; g < G; g++) {
            uint256 cost = SCALE - ledger[g];
            uint256 m = marketability[g];
            if (m > cost) {
                // speculative value positive → accepted as money → marketability climbs (the feedback)
                uint256 nm = m + adopt;
                marketability[g] = nm > SCALE ? SCALE : nm;
            } else {
                // not worth holding speculatively → acceptance falls back toward consumption-only
                marketability[g] = m > decay ? m - decay : 0;
            }
            if (!isMoney[g] && marketability[g] >= SCALE) {
                isMoney[g] = true;
                emit MoneyEmerged(g, round);
            }
        }
        emit Step(round, marketability[0], marketability[1], marketability[2]);
    }

    // which good is emerging / has emerged as money (the most accepted)
    function emergedMoney() external view returns (uint8 best) {
        uint256 top;
        for (uint8 g = 0; g < G; g++) {
            if (marketability[g] > top) { top = marketability[g]; best = g; }
        }
    }
}
